export const dragQueens = [
 {  id: 1,
    name: "Ongina",
    season: 1,
    Instagram: "@ongina",
    instagramAddress: "https://instagram.com/ongina ",
    image: "https://i.pinimg.com/564x/62/03/7c/62037c10f28baf2ed2272e61995529ec.jpg",
    description:"she is a drag queen"
},
{  id: 2,
    name: "Jujubee",
    season: 2,
    Instagram: "@jujubeeonline",
    instagramAddress: "https://instagram.com/jujubeeonline ",
    image: "https://www.edgemedianetwork.com/display/viewimage_storyMain.php?id=291116&minwidth=600&maxwidth=1000",
    description:"she is a drag queen"
},
{  id: 3,
    name: "Alexis Mateo",
    season: 3,
    Instagram: "@miss_alexis_mateo",
    instagramAddress: "https://instagram.com/miss_alexis_mateo ",
    image: "https://i.pinimg.com/564x/14/57/cc/1457cc7ed70e037587b15cda742cc112.jpg",
    description:"she is a drag queen"
},
{  id: 4,
    name: "Manila Luzon",
    season: 3,
    Instagram: "@manilaluzon",
    instagramAddress: "https://instagram.com/manilaluzon ",
    image: "https://i.pinimg.com/564x/f3/77/0b/f3770b21fc070e13f8b3c109f3953361.jpg",
    description:"she is a drag queen"
},
{  id: 5,
    name: "Alyssa Edwards",
    season: 5,
    Instagram: "@alyssaedwards_1",
    instagramAddress: "https://instagram.com/alyssaedwards_1 ",
    image: "https://i.pinimg.com/564x/3e/e5/5a/3ee55abf92454b3ce6213ed304f2a5e2.jpg",
    description:"she is a drag queen"
},
{  id: 6,
    name: "Detox",
    season: 5,
    Instagram: "@theonlydetox",
    instagramAddress: "https://instagram.com/theonlydetox ",
    image: "https://i.pinimg.com/564x/c5/e8/df/c5e8df08a7276e79302a80f8e3543062.jpg",
    description:"she is a drag queen"
},
{  id: 7,
    name: "BenDeLaCreme",
    season: 6,
    Instagram: "@bendelacreme",
    instagramAddress: "https://instagram.com/bendelacreme ",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0U_QOBANoTRfqYBhdl5s1tNyQkT1diLF10A&usqp=CAU",
    description:"she is a drag queen"
},
{  id: 8,
    name: "Adore Delano",
    season: 6,
    Instagram: "@adoredelano",
    instagramAddress: "https://instagram.com/adoredelano ",
    image: "https://i.pinimg.com/564x/5e/5f/06/5e5f06642ca5e9a6452b6ebc7393c3af.jpg",
    description:"she is a drag queen"
},
{  id: 9,
    name: "Katya",
    season: 7,
    Instagram: "@katya_zamo",
    instagramAddress: "https://instagram.com/katya_zamo ",
    image:"https://i.pinimg.com/564x/a7/4c/6e/a74c6edc33b7955fd7b49b5c426979ba.jpg",
    description:"she is a drag queen"
},
{  id: 10,
    name: "Violet Chachki",
    season: 7,
    Instagram: "@violetchachki",
    instagramAddress: "https://instagram.com/violetchachki ",
    image: "https://fashionista.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cq_auto:good%2Cw_1200/MTUxMzk4OTgwOTY4Nzg1MTUx/bettie-page-lingerie-violet-chachki.png",
    description:"she is a drag queen"
},
{  id: 11,
    name: "Valentina",
    season: 9,
    Instagram: "@allaboutvalentina",
    instagramAddress: "https://instagram.com/allaboutvalentina ",
    image: "https://i.pinimg.com/564x/e5/4b/da/e54bda6d7d603b07fdb357965fcc1a6c.jpg",
    description:"she is a drag queen"
},
{  id: 12,
    name: "Sasha Velour",
    season: 9,
    Instagram: "@sashavelour",
    instagramAddress: "https://instagram.com/sashavelour ",
    image: "https://i.pinimg.com/564x/00/49/81/004981666b1a81996044ba8b44977305.jpg",
    description:"she is a drag queen"
},
{  id: 13,
    name: "Miz Cracker",
    season: 10,
    Instagram: "@miz_cracker",
    instagramAddress: "https://instagram.com/miz_cracker ",
    image: "https://i.pinimg.com/564x/12/93/4d/12934dabfc1022aa79d54927268de3d2.jpg",
    description:"she is a drag queen"
},
{  id: 14,
    name: "Scarlet Bobo",
    season: "Canada season 1",
    Instagram: "@itsscarlettbobo",
    instagramAddress: "https://instagram.com/itsscarlettbobo ",
    image:"https://i.pinimg.com/564x/25/7d/2a/257d2aff616c7910c6349b30d86cfb8c.jpg",
    description:"she is a drag queen"
},
{  id: 15,
    name: "Crystal Methyd",
    season: 12,
    Instagram: "@crystalmethyd",
    instagramAddress: "https://instagram.com/crystalmethyd ",
    image:"https://i.pinimg.com/564x/cc/54/9e/cc549ee926b209a3974daf554c678be0.jpg",
    description:"she is a drag queen"
},
{  id: 16,
    name: "Aiden Zhane",
    season: 12,
    Instagram: "@aidenzhane",
    instagramAddress: "https://instagram.com/aidenzhane",
    image:"https://i.pinimg.com/564x/78/45/c1/7845c13f956cfa77bd40725129a3a5cb.jpg",
    description:"she is a drag queen"
}
]